name: Release
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    name: "Build and release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Publish
        run: npx @vscode/vsce publish -p ${{ secrets.VSCE_PAT }}
